version: '2'
services:
    micojh001application-app:
        image: micojh001application
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://micojh001application-mysql:3306/micojh001application?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    micojh001application-mysql:
        extends:
            file: mysql.yml
            service: micojh001application-mysql
